# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bytový dům Na návsi
description: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
keywords: Svojetice, bydlení svojetice, byty, Na Návsi, lékař svojetice, doktor svojetice, bydlení, simekostav, budova
author: arkun.xyz
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://bydleniSvojetice.cz" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
